import mongoose from 'mongoose';

const checkpointSchema = new mongoose.Schema({
  week: {
    type: Number,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  description: String,
  tasks: [String],
  isCompleted: {
    type: Boolean,
    default: false
  }
}, { _id: false });

const weeklyContentSchema = new mongoose.Schema({
  week: {
    type: Number,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  subtopics: [String],
  tasks: [String],
  estimatedHours: {
    type: Number,
    required: true
  },
  learningGoals: [String]
}, { _id: false });

const resourceSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['video', 'article', 'documentation', 'course', 'interactive', 'book'],
    required: true
  },
  title: {
    type: String,
    required: true
  },
  url: {
    type: String,
    required: true
  },
  platform: String, // YouTube, Udemy, freeCodeCamp, etc.
  isPaid: {
    type: Boolean,
    default: false
  },
  rating: Number,
  duration: String // "3 hours", "10 mins", etc.
}, { _id: false });

const roadmapDurationSchema = new mongoose.Schema({
  durationMonths: {
    type: Number,
    required: true,
    enum: [3, 5]
  },
  weeklyHours: {
    type: Number,
    required: true
  },
  totalWeeks: {
    type: Number,
    required: true
  },
  weeklyContent: [weeklyContentSchema],
  checkpoints: [checkpointSchema],
  milestones: [{
    week: Number,
    title: String,
    description: String
  }]
}, { _id: false });

const skillRoadmapSchema = new mongoose.Schema(
  {
    skillName: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true
    },
    aliases: [String], // Alternative names for the skill
    difficulty: {
      type: String,
      required: true,
      enum: ['Beginner', 'Intermediate', 'Advanced'],
      index: true
    },
    category: {
      type: String,
      required: true,
      enum: [
        'Frontend',
        'Backend',
        'Full Stack',
        'Mobile',
        'DevOps',
        'Cloud',
        'Database',
        'Data Science',
        'Machine Learning',
        'Security',
        'Testing',
        'System Design',
        'Programming Language',
        'Other'
      ],
      index: true
    },
    shortDescription: {
      type: String,
      required: true
    },
    learningGoal: {
      type: String,
      required: true
    },
    prerequisites: [String],
    relatedSkills: [String],
    
    // Roadmap durations (3-month intensive, 5-month balanced)
    roadmaps: {
      threeMonth: roadmapDurationSchema,
      fiveMonth: roadmapDurationSchema
    },
    
    // Learning resources (generated by Gemini)
    learningResources: [resourceSchema],
    
    // Practice tasks & projects
    practiceTasks: [String],
    realWorldProjects: [String],
    
    // Interview prep
    interviewQuestions: [String],
    commonMistakes: [String],
    
    // Metadata
    popularityScore: {
      type: Number,
      default: 0,
      index: true
    },
    salaryImpact: {
      percentage: String, // "10-15%"
      basedOn: String // source of data
    },
    demandTrend: {
      type: String,
      enum: ['Rising', 'Stable', 'Declining', 'Unknown'],
      default: 'Unknown'
    },
    industryDemand: [{
      industry: String,
      demandLevel: {
        type: String,
        enum: ['Low', 'Medium', 'High', 'Very High']
      }
    }],
    
    // Resource generation status
    resourcesGenerated: {
      type: Boolean,
      default: false
    },
    lastResourceUpdate: Date,
    
    // User engagement
    viewCount: {
      type: Number,
      default: 0
    },
    enrollmentCount: {
      type: Number,
      default: 0
    },
    completionRate: {
      type: Number,
      default: 0
    }
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
);

// Indexes for efficient querying
skillRoadmapSchema.index({ category: 1, difficulty: 1 });
skillRoadmapSchema.index({ popularityScore: -1 });
skillRoadmapSchema.index({ resourcesGenerated: 1 });

// Virtual for total estimated hours
skillRoadmapSchema.virtual('totalHours').get(function() {
  if (this.roadmaps.threeMonth) {
    return this.roadmaps.threeMonth.weeklyContent.reduce((sum, week) => sum + week.estimatedHours, 0);
  }
  return 0;
});

// Static methods

/**
 * Get roadmap by skill name (case-insensitive)
 */
skillRoadmapSchema.statics.findBySkillName = async function(skillName) {
  const normalized = skillName.trim();
  
  // Try exact match first
  let roadmap = await this.findOne({ skillName: new RegExp(`^${normalized}$`, 'i') });
  
  // Try aliases
  if (!roadmap) {
    roadmap = await this.findOne({ aliases: new RegExp(`^${normalized}$`, 'i') });
  }
  
  // Try partial match
  if (!roadmap) {
    roadmap = await this.findOne({ skillName: new RegExp(normalized, 'i') });
  }
  
  return roadmap;
};

/**
 * Get roadmaps by category
 */
skillRoadmapSchema.statics.findByCategory = async function(category) {
  return this.find({ category }).sort({ popularityScore: -1 });
};

/**
 * Get popular roadmaps
 */
skillRoadmapSchema.statics.getPopular = async function(limit = 10) {
  return this.find()
    .sort({ popularityScore: -1, enrollmentCount: -1 })
    .limit(limit);
};

/**
 * Search roadmaps
 */
skillRoadmapSchema.statics.search = async function(query) {
  return this.find({
    $or: [
      { skillName: new RegExp(query, 'i') },
      { aliases: new RegExp(query, 'i') },
      { shortDescription: new RegExp(query, 'i') }
    ]
  }).sort({ popularityScore: -1 });
};

/**
 * Get roadmaps needing resource generation
 */
skillRoadmapSchema.statics.getNeedingResources = async function(limit = 10) {
  return this.find({ resourcesGenerated: false }).limit(limit);
};

// Instance methods

/**
 * Mark resources as generated
 */
skillRoadmapSchema.methods.markResourcesGenerated = async function() {
  this.resourcesGenerated = true;
  this.lastResourceUpdate = new Date();
  return this.save();
};

/**
 * Increment view count
 */
skillRoadmapSchema.methods.incrementViews = async function() {
  this.viewCount += 1;
  return this.save();
};

/**
 * Enroll user (increment enrollment count)
 */
skillRoadmapSchema.methods.enrollUser = async function() {
  this.enrollmentCount += 1;
  return this.save();
};

const SkillRoadmap = mongoose.model('SkillRoadmap', skillRoadmapSchema);

export default SkillRoadmap;